#Section 1

In [ ]:
print("This is my second class on AI")

This is my second class on AI


Function in Python

In [ ]:
def area_of_square (num):
  return num*num
print("the area is:",area_of_square(6))
print("the area of seond square is:", area_of_square(16))

the area is: 36
the area of seond square is: 256


def area_of_circle(num):
  return num*num
print("the area is:"

List in Python

In [ ]:
# Creating a list of fruits
fruits = ["apple", "banana", "Kiwi", "orange", "strewary"]
# Accessing elements
# print(fruits[0]) accessing first elements in the list
# print(fruits[4]) accessing 5th elements in the list.

# adding elements from list
fruits.append("mango")
print(fruits)

# Removing elements from list
fruits.remove("Kiwi")
print(fruits)

['apple', 'banana', 'Kiwi', 'orange', 'strewary', 'mango']
['apple', 'banana', 'orange', 'strewary', 'mango']


#**Tuples in Python**

In [ ]:
#**Dictionaries in Python**

In [ ]:
# Creating a Dictionary
student={
  "name": "Ram Prasai",
  "age" : 30,
  "Course" : "Computer Science"}
#Accessing alues of a particular key in a dictionary
print(student["age"])
student["age"]=55
print(student["age"])

print(student["address"])
student["address"] = "Kathmandu"
print(student["address"])

30
55


KeyError: 'address'

In [ ]:
num=int(input("what is the temperature c"))
def todays_temp(num):
  return num*9/5+32
print("the temperature in fahrenhit is:",todays_temp(num))

what is the temperature100
the temperature in fahrenhit is: 212.0


String Manipulation in Python(Tomorrow)

In [ ]:
num=int(input("what is the temperature f"))
def todays_temp(num):
  return (num-32)*5/9
print("the temperature in celcius is:",todays_temp(num))

what is the temperature f212
the temperature in celcius is: 100.0


In [ ]:
Birth year=int(input("what is your birth year"))
def age(birthyear):
  return 2025- birth year
print("your age is :",age(birth year))

what is your birth year2015
your age is : 10


In [ ]:
# Interest
principle = float(input("enter the principle Amount (P):"))
rate = float(input("enter the rate of interest(R) in % : "))
time = int(input("enter the period of time (T):"))
def interest(principle, rate,time):
  return (principle* rate* time)/100
print("the interest per year:",interest(principle,rate,time))

enter the principle Amount (P):10000
enter the rate of interest(R) in % : 12
enter the period of time (T):2
the interest per year: 2400.0


In [ ]:
#BMI Calculator
weight=float(input("enter your weight in kg:"))
height=float(input("enter your height in m:"))
def bmi(weight,height):
  return weight/(height*height)
print("your bmi is:",bmi(weight,height))

if bmi < 18.5:
    print("You are underweight.")
elif 18.5 <= bmi < 25:
    print("You have a normal weight.")
elif 25 <= bmi < 30:
    print("You are overweight.")
else:
    print("You are obese.")

enter your weight in kg:85
enter your height in m:1.3
your bmi is: 50.29585798816568


TypeError: '<' not supported between instances of 'function' and 'float'

In [ ]:
#Currency Converter
amount=float(input("enter amount in local currency"))
result=amount/132
print("amount in USD:",result)



enter amount in local currency10000
amount in USD: 75.75757575757575


In [ ]:
import random
print(random.randint(0,9))

8


 #*String* manipulation in Python

In [ ]:
# Creating a variable named "text"that contains leading and trailing spaces
text="   Hello Python  "
print(text)

#Lower()is used here to convert original text into lowercase
print(text.lower())

#strip() is used to remove leading and trailing spaces
print(text.strip())

#
print(text.replace("Python","Java"))
# Splitting and joining
#Function Chaining or Method chaining
splitted=text.strip().split()
print(splitted)

joined =" ".join(splitted)
print(joined)

   Hello Python  
   hello python  
Hello Python
   Hello Java  
['Hello', 'Python']
Hello Python


MODULAR PROGRAMMING IN PYTHON

In [ ]:
#importing math module
import math

square_root=math.sqrt(25)
print(int(square_root))


5


In [ ]:
floor=math.floor(3.7)
print("The florring of 3.7 is:",floor)

ceiling=math.ceil(3.7)
print("The ceiling of 3.7 is:",ceiling)

The florring of 3.7 is: 3
The ceiling of 3.7 is: 4


##Module alaising

In [ ]:
import matplotlib.pyplot as plt
plt.plot([1,2,3],[4,5,6])


Variable Alaising

In [ ]:
a=[1,2,3,4]
print(a)
b=a
b.append(5)
print(b)
print(a)

#homework: experiment with function/method aliasing

[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


Randoms in Python

In [ ]:
import random as rdn
print(rdn.randint(0,10))

10


In [ ]:
random_float=rdn.random()
print(random_float)

0.20312019093908362


In [ ]:
random_float_in_range=rdn.uniform(2.5,10.0)
print(random_float_in_range)

#Homework: Explore More Modules and function/Methods

8.718624188752756


#CREATING CUSTOM MODULES IN PYTHON

In [ ]:
#helper.py
%%writefile helperr.py
def add_numbers(a,b):
  return a+b

Writing helperr.py


In [ ]:
#main.py
import helperr
result= helperr.add_numbers(3,9)
print("The addition between these numbers is:",result)

The addition between these numbers is: 12


In [ ]:
#helper.py
%%writefile helper2.py
def sub_numbers(a,b):
  return a-b
def add_numbers(a,b):
  return a+b
def mul_numbers(a,b):
  return a*b
def dev_numbers(a,b):
  return a/b


Writing helper2.py


In [ ]:
#main.py
import helper2
result= helper2.sub_numbers(5,10)
result= helper2.add_numbers(5,10)
result= helper2.add_numbers(5,10)
result= helper2.mul_numbers(5,10)
result= helper2.dev_numbers(5,10)
print("The subctaction between these numbers is:",result)
print("The addition between these numbers is:",result)
print("The multiplication between these numbers is:",result)
print("The division between these numbers is:",result)

Subtraction: -5
Addition: 15
Multiplication: 50
Division: 0.5


#Import shuffle from random, create a list [10, 20, 30, 40], shuffle it and print.

import shuffle
random_list(10,20,30,40)
shuffle(random_list)
print(random_list)

In [ ]:
import random
numbers = [10, 20, 30, 40]
random.shuffle(numbers)
print(numbers)

[30, 20, 40, 10]


In [ ]:
#imprt math
import math
sine_30 = math.sin(math.radians(30))
print("Sine of 30 degrees:", sine_30)

Sine of 30 degrees: 0.49999999999999994


In [ ]:
%%writefile calc.py
def square(n):
  return n*n


Writing calc.py


In [ ]:
import calc
print(calc.square(8))

64


In [ ]:
import random
fruits_list = ["apple", "banana", "cherry", "date", "elderberry"]
random_fruit = random.choice(fruits_list)
print(random_fruit)

apple


In [ ]:
x=input("enter a number:")
print(10/0)

enter a number:10


ZeroDivisionError: division by zero

# File Handiling and ecceptions

#opening and Reading a file

In [ ]:
f=open("/content/Test.txt","r")
print(f.read())
f.close()

I am teaching!
I am reading!
I am working!
student are doing their task!


In [ ]:
f=open("/content/Test.txt","r")
print(f.readlines(2))
f.close()

['I am teaching!\n']


In [ ]:
with open("/content/Test.txt","r") as f:
  print(f.read())

I am teaching!
I am reading!
I am working!
student are doing their task!


# Writing to a file

In [ ]:
f=open("Re.txt","w")
f.write("This is a new line")
f.close()

In [ ]:
with open("Test.txt","w") as f:
  f.write("My Name is")

#Appending to file

In [ ]:
f=open("Test.txt","a")
f.write("\nThis is a new line")
f.close()

In [ ]:
f=open("Data.txt","r")
print(f.read())
f.close()

Nepal 
kathmandu
What is This
about myself


#DELETING TO A FILE/FOLDER

In [ ]:
import os
os.remove("Test.txt")

In [ ]:
  os.rmdir("/content/Delete_me")

NotADirectoryError: [Errno 20] Not a directory: '/content/Delete_me'

#EXCEPTION HANDLING

In [ ]:
try:
  print(x)
except:
  print("An exception occured")

10


#class work

In [ ]:
try:
  with open("Data.txt","r") as f:
    print(f.readlines())
except FileNotFoundError:
  print("File not found")

['Nepal \n', 'kathmandu\n', 'What is This\n', 'about myself']


In [ ]:
f=open("User.txt","w")
f.write("My Name is ...")
f.close()

In [ ]:
with open("User.txt","w") as f:
  print(f.write("next level"))

10


In [ ]:
try:
  with open("user.txt","w") as f:
    print(f.write("hi"))
except FileNotFoundError:
  print("File not found")

2


In [ ]:
try:
  with open("user_txt","r") as f:
    content=f.read()
    word=content.split()
    word_count=len(word)
    print("total no of word:", word_count)
except FileNotFoundError:
  print("File not found")

total no of word: 18


In [ ]:
try:
  with open("note.txt","a") as f:
    f.write("next level")
except FileNotFoundError:
  print("File not found")

In [ ]:
try:
  with open("number.txt","n")as f:
    add

#Numpy Basics

#Creating a numpy array and its attributes

In [ ]:
#Importing numpy libarary
import numpy as np
#creating a list named "my_list"
my_list=[1,3,5,7,9]
#creating a 1-D numpy array from "my_list"
my_arr=np.array(my_list)
#printing the array
print(my_arr)

#Creating a 0-D array
arr_0d=np.array(42)
print(arr_0d)

#Creating a 2-D array
arr_2d=np.array([1,2,3,4,5])
print(arr_2d)

#creating a 3-D array
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)

[1 3 5 7 9]
42
[1 2 3 4 5]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#creating array and  its attributes
arr=np.array()

#accessing and manipulating array elements

In [ ]:
#Accesing 1-D array elements
my_arr=np.array([1,3,5,7,9])
print(my_arr[2])


5


In [ ]:
#Accesing 2-D array elements

my_arr = np.array([[1, 3, 5, 7,], [1, 3, 5, 9]])
print(my_arr[1, 2])

5


In [ ]:
#Accessing 3-D array elements
my_arr=np.array([[[1,3,5,7],[1,3,5,9]]])
print(my_arr[0,1,2])

5


#Negative indesing

In [ ]:
#Accesing 2-D array elements with negative indexing
import numpy as np
my_arr=np.array([[1,3,5,7,],[1,3,5,9]])
print(my_arr[-1,-2])

5


#Slicing Arrays
#Important concepts while slicing array
#array[start:end]
#array[start:end:step]

In [ ]:
#slicing a 1-D numpy Array
arr=np.array([1,3,5,7,9,11,13,15])
print(arr[1:5])   #slicing
print(arr[1:5:2]) #slicing with step
print(arr[0:-1])  #Negative

[3 5 7 9]
[3 7]
[ 1  3  5  7  9 11 13]


In [ ]:
#slicing a 2-D Numby Array
arr=np.array([[1,3,5,7],[2,4,6,8]])
print(arr[1,1:-1])


[4 6]


In [ ]:
#third elements and slice from index 1,3
import numpy as np
arr=np.array([1,3,5,6,9,7,11])
print(arr[2])
print(arr[1:4])

5
[3 5 6]


#Homework:Expe

In [ ]:
#2D numpy arry (3,3) with random between 1 and 10
#replace value greater then 5 with 0
import numpy as np
arr = np.random.randint(1, 11, size=(3, 3))
print(arr)
arr[arr > 5] = 0
print(arr)

[[7 6 1]
 [6 3 2]
 [1 8 4]]
[[0 0 1]
 [0 3 2]
 [1 0 4]]


In [20]:
#1D numpy array to compute the element-wise sum and print both result
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [21]:
np.random.rand(2,2)

array([[0.27602546, 0.68582685],
       [0.20229393, 0.80706861]])

#Day 6
#hands-on practice: pandas and Matplotlib
#Exercise 1: Ceating a Pandas Seres
#pandas Series=1D array with labels

In [22]:
import pandas as pd
scores=pd.Series([78,85,92,76,88], index=["Maths","Science","English","History"])
print(scores)

ValueError: Length of values (5) does not match length of index (4)

In [ ]:
#task 1: Create a Pandas series with values[10,20,30,40] and Indices["A","B","c","D"]. Print series

#exercise 2: Creating a Pandas Data Frame
#dataframe is in a table format

In [26]:
data={"name":["Arav","Bikram","cherry"],
      "age":[15,56,12],
    "City":["Kathmandu","Bhaktapur","Lalitpur"],
      "Country":["Nepal","India","USA"]}
      #Turning the dictionary into a dataframe
df=pd.DataFrame(data)
#Printing the dataframe
print(df)

     name  age       City Country
0    Arav   15  Kathmandu   Nepal
1  Bikram   56  Bhaktapur   India
2  cherry   12   Lalitpur     USA


In [25]:
#Task 2: Craeate a Dataframe with colums "City"(["paris","tokyo", "Sydney"]) and "Population" ([2.1,37.4,5.3]). Print the Data frame
impot pandsa as pd
df=pd.DataFrame({"City":["paris","tokyo","Sydney"],"Population":[2.1,37.4,5.3]})
print(df)

SyntaxError: invalid syntax (<ipython-input-25-22bf55991c32>, line 2)

#Exercise 3:Filterin Data in data frame

In [27]:
data={"name":["Arav","Bikram","cherry"],
      "age":[15,56,12],
    "City":["Kathmandu","Bhaktapur","Lalitpur"],
      "Country":["Nepal","India","USA"]}
      #Turning the dictionary into a dataframe
df=pd.DataFrame(data)
#Printing the dataframe
print(df)

#Filtering
filter=df["age"]>18
print(df[filter])

#Task 3: create a dataframe with columns "Name"(["eve","Frank","grace"])
#and "age" ([19,23,20]). Filter rows where age is greater than 20 and print the
#result.

     name  age       City Country
0    Arav   15  Kathmandu   Nepal
1  Bikram   56  Bhaktapur   India
2  cherry   12   Lalitpur     USA
     name  age       City Country
1  Bikram   56  Bhaktapur   India


#Exercise 4:Reading and Processing a CSV file

In [32]:
import io
#Creating a CSV file
csv_data="""
name, Grade
Sushil,1
Arpan,2
Rohit,3
"""

#Reading a CSC file
df=pd.read_csv(io.StringIO(csv_data))
print(df)

#Calculate average grade
avrage_grade=df["Grade"].mean()
print("Average grade:",average_grade)

# Task 4: Simulate a CSV

     name   Grade
0  Sushil       1
1   Arpan       2
2   Rohit       3


KeyError: 'Grade'

#Project

In [1]:
from word2number import w2n
from datetime import datetime

def get_year_from_input(user_input):
    try:
        # Try converting directly to integer
        return int(user_input)
    except ValueError:
        try:
            # Convert words to number
            return w2n.word_to_num(user_input.lower())
        except ValueError:
            print("Invalid input format.")
            return None

def get_age_group(age):
    if age < 0:
        return "Invalid age. Please enter a valid year of birth."
    elif age <= 12:
        return "Child"
    elif age <= 19:
        return "Teenager"
    elif age <= 35:
        return "Young Adult"
    elif age <= 59:
        return "Adult"
    else:
        return "Senior Citizen"

def main():
    user_input = input("Enter your birth year (e.g., 2005 or 'Two Thousand Five'): ")
    birth_year = get_year_from_input(user_input)

    if birth_year is not None:
        current_year = datetime.now().year
        age = current_year - birth_year

        if age < 0:
            print("You entered a year in the future. Please try again.")
        else:
            group = get_age_group(age)
            print(f"Your age is: {age}")
            print(f"You belong to the '{group}' age group.")

if __name__ == "__main__":
    main()

SyntaxError: invalid non-printable character U+00A0 (<ipython-input-1-e20c78bc46b8>, line 46)

#Project Age Group Chaker

In [3]:
# Step 1: Prompt the user for input with error handling
try:
    age = int(input("Please enter your age: "))

    # Step 2: Define the function
    def age_group(age):
        if age <= 12:
            return "Child"
        elif age <= 19:
            return "Teenager"
        elif age <= 64:
            return "Adult"
        else:
            return "Senior"

    # Step 3: Get result and print it
    result = age_group(age)
    print(f"Based on your age, you are classified as: {result}")

except ValueError:
    print("Invalid input! Please enter a valid number for age.")

Please enter your age: 2025
Based on your age, you are classified as: Senior


In [1]:
from word2number import w2n
from datetime import datetime
def say_amazing(year):
   amazing={
1980:"Ic2onic music and films defined the era—Michael Jackson’s Thriller (1982), Back to the Future (1985), and the rise of MTV. The fall of the Berlin Wall (1989) symbolized the end of the Cold War.",
1990:"The World Wide Web went public (1991), and Netscape (1994) made the internet accessible. The first text message was sent in 1992. Amazon (1994) and Google (1998) were founded, reshaping commerce and information.",
2000:"The iPod (2001) and iPhone (2007) revolutionized music and mobile communication. Facebook (2004) and YouTube (2005) transformed social media and content sharing. Wikipedia (2001) democratized knowledge",
2010:"Tesla’s Model S (2012) accelerated electric vehicle adoption. AI advancements, like AlphaGo defeating a Go champion (2016), marked tech breakthroughs.",
2020:"SpaceX’s reusable rockets and Starlink (2020s) expanded space access and global internet. AI models like ChatGPT (2022) and Grok 3 (2024) transformed human-machine interaction."}
   if year<1981:
     print(amazing[1980])
     print(amazing[1990])
     print(amazing[2000])
     print(amazing[2010])

     print(amazing[2020])
   elif year<1991:
     print(amazing[1990])
     print(amazing[2000])
     print(amazing[2010])
     print(amazing[2020])

   elif year<2001:
     print(amazing[2000])
     print(amazing[2010])
     print(amazing[2020])
   elif year<2011:
     print(amazing[2010])
     print(amazing[2020])
   elif year>2024:
      print(" ")
   else:
     print(amazing[2020])
def get_year_from_input(user_input):
    try:
        # Try converting directly to integer
        return int(user_input)
    except ValueError:
        try:
            # Convert words to number given by user
            return w2n.word_to_num(user_input.lower())
        except ValueError:
            print("Invalid input format.")
            return None

def get_age_group(age):
    if age<0:
        return "Invalid age. Please enter a valid year of birth."
    if age == 0:
        return "You are infant"
    elif age <= 12:
        return "Child"
    elif age <= 19:
        return "Teenager"
    elif age <= 35:
        return "Young Adult"
    elif age <= 59:
        return "Adult"
    elif age<=100:
        return "Senior Citizen"
    else:
        raise ValueError

def main():
    user_input = input("Enter your birth year (e.g., 2005 or 'Two Thousand Five'): ")
    birth_year = get_year_from_input(user_input)
    if birth_year<1925:
        raise ValueError
    else:
     say_amazing(birth_year)
     if birth_year is not None:
        current_year = datetime.now().year
        age = current_year - birth_year

        if age < 0:
            print("You entered a year in the future. Please try again.")
        else:
            group = get_age_group(age)
            print(f"Your age is: {age}")
            print(f"You belong to the '{group}' age group.")

try:
    main()
except:
    print("You entered wrong value")

ModuleNotFoundError: No module named 'word2number'