# Hands-on Practice: Linear Algebra for AI

In [1]:
#Exercise: Working with Scalar And vactors

In [4]:
import numpy as np

#creating a Scaler
scaler=9
print(scaler)

#Creating a Cector
vector=np.array([1,2,3])
print(vector)

#scaling vector with a scaler aka. scaled vector
scaled_vector=vector*scaler
print(scaled_vector)

9
[1 2 3]
[ 9 18 27]


#Cector Addision and Substraction

#Matrix Creation and simple operation

In [20]:
from re import sub
Matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Matrix1)

add_matrix=Matrix1+matrix2
print(add_matrix)

sub_matrix=Matrix1-matrix2
print(sub_matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#Matric Multipication

In [14]:
matric1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[1,2,3],[4,5,6],[7,8,9]])

product=np.dot(matric1,matrix2)
print(product)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [17]:
#Task 4: create two 2x2 matrices[[1,0],[0,1]and [[2,3],[4,5]]
matric=np.array([[1,0],[0,1]])
matrix2=np.array([[2,3],[4,5]])
print(matric)
print(matrix2)


[[1 0]
 [0 1]]
[[2 3]
 [4 5]]


In [19]:
# Define two 2x2 matrices
A = [[0, 1 ],
     [1, 2]]

B = [[1, 0],
     [2, 1]]
ans=[]

matrice=np.dot(A,B)
print(matrice)

[[2 1]
 [5 2]]


#Exercise 5:

In [21]:
identity=np.eye(2,dtype=)
print(identity)

matrix1=np.array([[1,2],[3,4]])
print(matrix1)

product=np.dot(identity,matrix1)
print(product)

#task 5: Create a 2x3 matrix[]

SyntaxError: invalid syntax (<ipython-input-21-b0e52c4c1831>, line 1)

#Matrix Inverse

In [25]:
matirx1=np.array([[2,4],[5,7]])
# print(matirx1)

# inverse=np.linalg.inv(matirx1)
# print(inverse)

identity=np.dot(matirx1,inverse)
print(identity)

[[2.  0. ]
 [0.5 1.5]]
